### ISSUE TITLE
Mail Sent, no entry in submissions, when specific text found in message body template

### ISSUE THREAD

**Issue by johnglow** [hexxu-dev/UFormKit#3] opened 2024-11-04 11:44 UTC
I added this text to the "message body" template 

```
From: [name] 
Email: [email]
Telephone: [telephone]
Organisation: [organisation]

Message Body:
[your-message]

Accepts marketing communications: [marketingAccept] 

("A" = B, "_remote_ip" = Y)

_-_-_-_-_-_- Technical details _-_-_-_-_-_-

Remote IP: [_remote_ip]
User Agent: [_user_agent]
Url: [_url]
```

The user is shown the thanks page
The email was received 
However, **there was no entry in the submissions list**

When removing this line an entry is added to the submissions

`("A" = B, "_remote_ip" = Y)`

The term "_remote_ip" can be changed with another field such as "organisation" and it also breaks

The submissions should be added no matter the text in "message body"

**Comment by hexxu-dev** [comment] 2024-11-05 15:28
Hello, we were unable to reproduce the bug on our end. However, we did notice an issue with sorting the results, which might cause the latest results not to appear at the top as expected, potentially leading to confusion (although they should be saved correctly). Could you please try using the latest version, 1.0.6, and check if you’re still experiencing the issue?

**Comment by johnglow** [comment] 2024-11-05 17:25
Submission is not added to the list in version 1.0.6 under the following circumstances 

Message is

```
From: [name] 
Email: [email]
Telephone: [telephone]
Organisation: [organisation]

Message Body:
[your-message]

Accepts marketing communications: [marketingAccept]

("A" = B, "_remote_ip" = Y)


_-_-_-_-_-_- Technical details _-_-_-_-_-_-

Remote IP: [_remote_ip]
User Agent: [_user_agent]
Url: [_url]
```

Template is

```
<div class="row">

<div class="form-group col-lg-6"> 
<label>Name</label>
    [text* name placeholder "Name"] 
</div>

<div class="form-group col-lg-6"> 
<label>Email address</label>
    [email* email placeholder "Email"] 
</div>

<div class="form-group col-lg-6"> 
<label>Telephone number</label>
    [tel telephone placeholder "Telephone"] 
</div>

<div class="form-group col-lg-6"> 
<label>Organisation name</label>
  [text* organisation placeholder "Organisation Name"]
</div>

<div class="form-group col-lg-12"> 
<label for="your-message">Your message</label>
[textarea your-message id:your-message placeholder "Enter your message here"] 
</div>

<div class="form-group col-lg-12"> 
[acceptance your-consent*] I accept the <a target="_blank" href="/terms-conditions/" title="Opens in new tab">terms & conditions</a> [/acceptance]
</div>

<div class="form-group col-lg-12"> 
[acceptance marketingAccept optional]Opt into marketing communications[/acceptance]
</div>

<div class="form-group col-lg-12"> 
[submit "Submit"]
</div>

</div>
```

With settings 

Use recaptcha: true
Use Honeypot: true

Use HTML content type: false
Exclude lines with blank mail-tags from output: false
File attachments: blank
Exclude links in message: false

Do not store data: false
Demo mode: false
Redirect to page: Set to a thank you page

Note that the submission is added if the new option "Exclude links in message" is true.

**Comment by hexxu-dev** [comment] 2024-11-06 13:04
It seems there is an issue with the message length. To resolve this, please follow these steps:
 
Navigate to the Settings section in the backoffice and click on **UForm Submission** Document Type.
Open the Property settings for the Message property.
Edit the Label (string) and change its Value type from "String" to "Long string".
Save all changes to apply the modifications.

Once saved, try again to check if the issue is resolved.

**Comment by johnglow** [comment] 2024-11-06 13:52
Amazing! Our team say that tweak fixes the issue.

**Comment by hexxu-dev** [comment] 2024-11-07 09:43
Thanks, we are closing the issue now. If you feel something is still not ok with it, please reopen or create a new one.

**Closed as completed by hexxu-dev** 2024-11-07 09:43 UTC
